services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: reviews
      POSTGRES_USER: reviews
      POSTGRES_PASSWORD: reviews
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reviews -d reviews"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: reviews
      DB_PASSWORD: reviews
      DB_NAME: reviews
      SEED_ON_BOOTSTRAP: "true"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
